# Generated by Django 6.0.6 on 2026-06-16 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='damage_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_damage_record',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='paint_changed_parts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Boyalı parça sayısı'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='replaced_parts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Değişen parça sayısı'),
        ),
        migrations.CreateModel(
            name='ListingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fake', 'Sahte İlan'), ('sold', 'Satılmış Araç'), ('wrong_info', 'Yanlış Bilgi'), ('spam', 'Spam'), ('other', 'Diğer')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='listings.listing')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listing Report',
                'verbose_name_plural': 'Listing Reports',
                'db_table': 'listing_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
